---
- name: Install unzip
  package:
    name: unzip
    state: present
    update_cache: yes
    force: true
- name: Ensure certificates folder exists
  file:
    path: "{{ item }}"
    state: directory
    owner: consul
    group: consul
    mode: 0755
  with_items:
    - "{{ consul_template_config_dir }}"
    - "{{ consul_template_template_dir }}"
    - "{{ consul_template_certs_dir }}"
    - "{{ consul_template_rendered_dir }}"
    - "{{ consul_template_dir }}"
- name: Get consul-template archive
  get_url:
    url: https://releases.hashicorp.com/consul-template/{{ consul_template_version }}/{{ consul_template_archive }}
    dest: "{{ consul_template_dir }}"
    mode: 0644
    decompress: true
    force: true
- name: Uncompress archive
  unarchive:
    remote_src: true
    src: "{{ consul_template_dir }}/{{ consul_template_archive }}"
    dest: "/usr/bin"
    owner: root
    group: root
    mode: 0755
- name: Create systemd service for consul-template
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: consul
    group: consul
    mode: 0644
  with_items:
    - src: templates/consul-template.service.j2
      dest: "{{ consul_template_service_file }}"
  notify: reload systemctl
- name: Copy consul-template configs
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: consul
    group: consul
    mode: 0644
  with_items:
    - src: templates/config.hcl.j2
      dest: "{{ consul_template_config_dir }}/config.hcl"
  notify: restart consul-template
- name: copy vault certs
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: consul
    group: consul
    mode: 0644
  with_items:
    - src: files/vault-ca.pem
      dest: "{{ consul_template_certs_dir }}/vault-ca.pem"
  notify: restart consul-template
- name: Ensure consul-template is running
  service:
    name: consul-template
    state: started
    enabled: yes
