module "haproxy_master" {
  source        = "../modules/lxc"
  lxc_count     = 1
  target_nodes  = var.PM_MASTER_NODE
  hostname      = "haproxy-master"
  startup_order = "order=1"
  ostemplate    = var.LXC_TEMPLATE
  password      = var.LXC_PASSWORD
  cores         = var.CORES
  memory        = var.MEMORY
  searchdomain  = var.LOCAL_DOMAIN
  nameserver    = var.NAMESERVER
  tags          = var.MASTER_TAGS
  storage       = var.STORAGE_NAME
  size          = var.STORAGE_SIZE
  iname         = var.INTERFACE_NAME
  bridge        = var.BRIDGE_NAME
  ips           = var.MASTER_IP
  cidr          = var.CIDR_BLOCK
  gw            = var.GATEWAY
  public_key    = var.public_key
}

module "haproxy_backup" {
  source        = "../modules/lxc"
  lxc_count     = var.BACKUP_COUNT
  target_nodes  = var.PM_BACKUP_NODES
  hostname      = "haproxy-backup"
  startup_order = "order=1"
  ostemplate    = var.LXC_TEMPLATE
  password      = var.LXC_PASSWORD
  cores         = var.CORES
  memory        = var.MEMORY
  searchdomain  = var.LOCAL_DOMAIN
  nameserver    = var.NAMESERVER
  tags          = var.BACKUP_TAGS
  storage       = var.STORAGE_NAME
  size          = var.STORAGE_SIZE
  iname         = var.INTERFACE_NAME
  bridge        = var.BRIDGE_NAME
  ips           = var.BACKUP_IPS
  cidr          = var.CIDR_BLOCK
  gw            = var.GATEWAY
  public_key    = var.public_key
}
