# -*- mode: ruby -*-
# vi: set ft=ruby :

# Create 2 Ubunutu 20.04 VMs to test ansible
# We force the MAC as Hyper-v provider lacks the ability to set IP address
# https://developer.hashicorp.com/vagrant/docs/providers/hyperv/configurationz
# We can set DHCP to provide static IP addresses to these machines (DHCP not included)
Vagrant.configure("2") do |config|

	config.vm.define "server" do |server|
		server.vm.box = "generic/ubuntu2004"
		server.vm.provider "hyperv" do |hv|
			hv.cpus = "1"
			hv.memory = "2048"
			hv.enable_enhanced_session_mode = true
			hv.mac = "00:15:5d:38:02:12"
			hv.vmname = "server"
		end
        config.vm.provider "virtualbox" do |vb|
            vb.cpus = "1"
            vb.memory = "2048"
            vb.base_mac = "00:15:5d:38:02:12"
            vb.name = "server"
        end
	end

	config.vm.define "client" do |client|
		client.vm.box = "generic/ubuntu2004"
		client.vm.provider "hyperv" do |hv|
			hv.cpus = "1"
			hv.memory = "2048"
			hv.enable_enhanced_session_mode = true
			hv.mac = "00:15:5d:38:02:13"
			hv.vmname = "client"
		end
        config.vm.provider "virtualbox" do |vb|
            vb.cpus = "1"
            vb.memory = "2048"
            vb.base_mac = "00:15:5d:38:02:13"
            vb.name = "client"
        end
	end

	# Uncomment this section to add a local public key as an authorized key on the VM
	config.vm.provision "file" do |f|
		f.source = "./id_rsa.pub"
		f.destination = "~/.ssh/authorized_keys"
	end
  
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  # config.vm.box = "base"
  # config.vm.box = "generic/debian10"
  # config.vm.box = "hashicorp/bionic64"
end
