version: '3.7'

services:
  devcontainer:
    user: dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DC_USER: dev

    volumes:
      # Forwards the local Docker socket to the container.
      - /run/docker.sock:/var/run/docker-host.sock 
      # Update this to wherever you want VS Code to mount the folder of your project
      - ../:/terraform/:cached
      - ~/.ssh:/home/dev/.ssh
      - terraform_vscode_extension:/home/dev/.vscode-server/extensions
      - terraform_vscode_insider_extension:/home/dev/.vscode-server-insiders/extensions
      # Persist bash history
      - terraform_bash_history:/home/dev/.bash_history

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity 

    # Uncomment the next four lines if you will use a ptrace-based debuggers like C++, Go, and Rust.
    cap_add:
     - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    network_mode: host

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  terraform_vscode_extension:
  terraform_vscode_insider_extension:
  terraform_bash_history:
