---
- name: copy nomad server config
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: vault
    group: vault
    mode: 0644
  with_items:
    - src: templates/server.hcl.tpl.j2
      dest: "{{ vault_agent_templates_dir }}/server.hcl.tpl"
    - src: templates/nomad-server-template.hcl.j2
      dest: "{{ vault_dir }}/nomad-server-template.hcl"
  notify: restart nomad
- name: Make sure nomad is running
  service:
    name: nomad
    state: started
    enabled: yes
