---
# tasks file for nomad-client
- name: Copy Nomad config
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: nomad
    group: nomad
    mode: 0644
  with_items:
    - src: templates/client.hcl.j2
      dest: "{{ nomad_dir }}/client.hcl"
  notify: restart nomad
- name: Add Nomad user to docker group
  ansible.builtin.user:
    append: true
    groups: docker
    name: nomad
  when: docker_installed
- name: Make sure nomad is running
  service:
    name: nomad
    state: started
    enabled: yes