---
- hosts: localhost
  connection: local
  become: false
  gather_facts: false
  roles:
    - retry
  vars:
    server_group: "{{ groups['nomad-server'] }}"
- hosts: nomad-server
  become: yes
  roles:
    - gpg
    - firewalld
    - consul-client
    - nomad-server
  vars:
    ports:
      - 4646/tcp
      - 4647/tcp
      - 4648/tcp
    consul_template_user: root
